In [1]:
import numpy as np
from scratchNNlib.Layers import Dropout

In [2]:
b = Dropout(0.3)

In [3]:
a = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]).T

In [4]:
b(a)

array([[ 1],
       [ 2],
       [ 3],
       [ 0],
       [ 5],
       [ 6],
       [ 0],
       [ 8],
       [ 9],
       [10]])

In [5]:
b.last_architecture

array([[1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1]])

In [6]:
b.backward(a, 0.1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])